---
title: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ISLR)
d1=Auto
str(d1)

# remove factor last col
d2 = d1[,-9] 

# cylinders and year are also factors
```
### Basic stats 

```{r}
# make window wide
summary(d2)

# only means
apply(d2,2,mean)
# only mpg
summary(d2$mpg)
```
\newpage
## PLOTTING
```{r fig_width=3, fig_height=2}

# scatterplot

# plot(cylinders, mpg)        # gives Error 
plot(d2$cylinders, d2$mpg)

# boxplot
d2$cylinders=factor(d2$cylinders)
plot(mpg~cylinders,d2)

# histogram
mpg = d2$mpg
hist(mpg)
hist(mpg,freq=F)  # not relative freqs 

h1=hist(mpg,freq=F)
h1$breaks         # [1] 5 10 15 20 25 30 35 40 45 50
# not relative freq since bars width is not equal to 1
```
```{r, echo=FALSE}
hh <-hist(mpg)
```
```{r, echo=TRUE}
hh$counts = hh$counts/sum(hh$counts)
plot(hh)

# increase axes limits
plot(hh,xlim=c(0,60),ylim=c(0,0.25))

# add normal density
width1 = hh$breaks[2]-hh$breaks[1]
mu = mean(mpg)
stdev = sd(mpg)
plot(hh,xlim=c(0,60),ylim=c(0,0.3),main="")
curve(dnorm(x,mu,stdev)*width1,col="red",add=T)
grid()

# or use

# install.packages("HistogramTools")
library(HistogramTools)
PlotRelativeFrequency(hist(mpg))

# scatterplot

plot(d2$weight,d2$horsepower)

# change point character
plot(horsepower~weight,d2,pch=19,cex=0.5)
grid()

unique(d2$origin)      # [1] 1 3 2
plot(horsepower~weight,d2,pch=19,cex=0.5,col=origin)
grid()

# legend
label = c("American","European","Japanese")
color = c(1,2,3)
char = c(19,19,19)
legend("bottomright",label,pch=char,cex=0.6,col=color)

# or
# legend(4500,75,label,pch=char,cex=0.6,col=color) 

# Regression line
plot(horsepower~weight,d2,pch=19,cex=0.5)
m1=lm(horsepower~weight,d2)
coefficients(m1)
abline(m1)
abline(m1,col="red")
abline(m1,col="red",lwd=2)
grid()

# predict horsepower 
head(d2,3)

newval = data.frame(weight=3000)
predict(m1,newval)   # 105.34

          
# outliers
res=resid(m1)
idx=which(res==max(res))   # 14

# locator
# identify(d2$weight,d2$horsepower,rownames(d2),cex=0.5)  # rownames is default id
# identify(d2$weight,d2$horsepower,d2$horsepower,cex=0.5)
# d2[14,]

# label all points
text(horsepower~weight,data=d2,labels=rownames(d2),pos=1,offset=0.25,cex=0.5)

# just label the outlier
plot(horsepower~weight,d2,pch=19,cex=0.5)
abline(m1,col="red")
label = rep("",392)
res   = resid(m1)
idx   = which(res==max(res))
label[idx]=idx
text(horsepower~weight,d2,labels=label,pos=1,offset=0.5,cex=0.6,col=2)

# pairs of scatterplots
pairs(d2)
# only numeric variables
pairs(~ mpg + displacement + horsepower + weight + acceleration,d2,pch=19,cex=0.5)
# change point character
pairs(~ mpg + displacement + horsepower + weight + acceleration,d1,pch=19,cex=0.5,col=d1$origin)

# load panel.hist() function
d3=d2[,-c(2,7:9)]  # remove factors
#pairs(d3,panel = panel.smooth,cex = 0.6,pch = 19,diag.panel = panel.hist,cex.labels = 0.8,font.labels = 1)

# use scatterplotMatrix() from library car
library(car)
scatterplotMatrix(~ mpg + displacement + horsepower + weight + acceleration,d2,pch=19,cex=0.5)
# mpg, displacement, hp, weight, acceleration seem correlated

# change diagonal to histograms
scatterplotMatrix(~ mpg + displacement + horsepower + weight + acceleration,d2,pch=19,cex=0.5,diagonal="histogram")


# covariance matrix
d3=d2[,-c(2,7,8)]
cov(d3)

# correlation matrix
cor(d3)

# boxplots
d3=d2
d3$origin=as.factor(d3$origin)
d3$year  =as.factor(d3$year)
d3$cylinders=as.factor(d3$cylinders)
plot(mpg~year,d3)
plot(mpg~cylinders,d3)


# outliers
plot(mpg~origin,d3)        # same as
boxplot(mpg~origin,d3)
Boxplot(mpg~origin,d3)     # library(car) required

# list outliers description
a=Boxplot(mpg~origin,d3)
d3[a,]


# normality
qqnorm(d2$mpg)
qqline(d2$mpg)
grid()
hist(d2$mpg)

par(mfrow=c(2,1))
hist(d2$mpg,xlab="",main="mpg distribution")
boxplot(d2$mpg,horizontal=T,axes=F)
par(mfrow=c(1,1))

# compare sample vs theoretical quantiles
x = scale(d2$mpg)
mean(x)   # 0
var(x)

qqnorm(x)
# change limits
qqnorm(x,ylim=c(-3,3))
qqline(x)
grid()

a = seq(0,1,0.1)
a

quantile(x,a)
qnorm(a)
```
