---
title: "599final_3"
author: "Shaoqian Chen"
date: "4/24/2020"
output: html_document
---

```{r}
# Helper packages
library(dplyr)       # for data manipulation
library(ggplot2)     # for data visualization
library(stringr)     # for string functionality

# Modeling packages
library(yardstick)
library(cluster)     # for general clustering algorithms
library(factoextra)  # for visualizing cluster results
library(dslabs)
```


```{r}
mnist <- dslabs::read_mnist()
#str(mnist$train)
#summary(mnist$train)
```



```{r}
#set.seed(1)
features <- mnist$train$images
#str(features)
```


```{r}
# Use k-means model with 10 centers and 10 random starts
mnist_clustering <- kmeans(features, centers = 10, nstart = 10)
# Print contents of the model output
str(mnist_clustering)
```



```{r}
# Extract cluster centers
mnist_centers <- mnist_clustering$centers

```



```{r}

# Plot typical cluster digits
par(mfrow = c(2, 5), mar=c(0.5, 0.5, 0.5, 0.5))
layout(matrix(seq_len(nrow(mnist_centers)), 2, 5, byrow = FALSE))
for(i in seq_len(nrow(mnist_centers))) {
  image(matrix(mnist_centers[i, ], 28, 28)[, 28:1], 
        col = gray.colors(12, rev = TRUE), xaxt="n", yaxt="n")
}
```

```{r}
# Create mode function
mode_fun <- function(x){  
  which.max(tabulate(x))
}

mnist_comparison <- data.frame(
  cluster = mnist_clustering$cluster,
  actual = mnist$train$labels
) %>%
  group_by(cluster) %>%
  mutate(mode = mode_fun(actual)) %>%
  ungroup() %>%
  mutate_all(factor, levels = 0:9)
```

```{r}
# Create confusion matrix and plot results
yardstick::conf_mat(
  mnist_comparison, 
  truth = actual, 
  estimate = mode
) %>%
  autoplot(type = 'heatmap')
```
```{r}
#str(mnist$train)
str(mnist$train$images)
str(mnist$train$labels)

mnist$train$labels[sample(10000),]
str(features)
```

